import { Tool, ToolCategory } from '@/types'

export const TOOL_CATEGORIES: ToolCategory[] = [
  {
    id: 'network',
    name: 'Network & Security',
    description: 'Network diagnostics, security analysis, and connectivity tools',
    icon: 'Globe',
    color: 'bg-blue-500',
  },
  {
    id: 'developer',
    name: 'Code & Development',
    description: 'Code formatting, validation, and development utilities',
    icon: 'Code',
    color: 'bg-green-500',
  },
  {
    id: 'seo',
    name: 'SEO & Marketing',
    description: 'SEO analysis, content optimization, and marketing tools',
    icon: 'Search',
    color: 'bg-purple-500',
  },
  {
    id: 'data',
    name: 'Data & Conversion',
    description: 'Data processing, format conversion, and analysis tools',
    icon: 'Database',
    color: 'bg-orange-500',
  },
  {
    id: 'image',
    name: 'Image & Media',
    description: 'Image processing, optimization, and media tools',
    icon: 'Image',
    color: 'bg-pink-500',
  },
  {
    id: 'utility',
    name: 'Utilities & Generators',
    description: 'General purpose utilities and content generators',
    icon: 'Settings',
    color: 'bg-gray-500',
  },
]

export const ADVANCED_TOOLS: Tool[] = [
  // Network & Security Tools (6 tools)
  {
    id: 'whats-my-ip',
    name: "What's My IP Address",
    description: 'Get your public IP address with detailed geolocation information and ISP details',
    category: TOOL_CATEGORIES[0],
    icon: 'MapPin',
    path: '/whats-my-ip',
    featured: true,
    popular: true,
    keywords: ['ip address', 'my ip', 'public ip', 'geolocation', 'isp info'],
  },
  {
    id: 'ssl-checker',
    name: 'SSL Certificate Checker',
    description:
      'Analyze SSL certificates, check expiration dates, and validate certificate chains',
    category: TOOL_CATEGORIES[0],
    icon: 'Shield',
    path: '/ssl-checker',
    popular: true,
    keywords: ['ssl certificate', 'https checker', 'certificate validation', 'ssl analysis'],
  },
  {
    id: 'port-scanner',
    name: 'Port Scanner & Service Detection',
    description: 'Scan open ports on any domain or IP address with service identification',
    category: TOOL_CATEGORIES[0],
    icon: 'Scan',
    path: '/port-scanner',
    keywords: ['port scanner', 'network scan', 'open ports', 'service detection'],
  },
  {
    id: 'dns-lookup',
    name: 'Advanced DNS Lookup',
    description: 'Complete DNS record analysis including A, AAAA, MX, CNAME, TXT, and NS records',
    category: TOOL_CATEGORIES[0],
    icon: 'Globe',
    path: '/dns-lookup',
    keywords: ['dns lookup', 'dns records', 'domain analysis', 'nameserver check'],
  },
  {
    id: 'website-monitor',
    name: 'Website Uptime Monitor',
    description:
      'Monitor website availability, response times, and get detailed performance metrics',
    category: TOOL_CATEGORIES[0],
    icon: 'Activity',
    path: '/website-monitor',
    featured: true,
    keywords: ['uptime monitor', 'website monitoring', 'performance check', 'availability test'],
  },
  {
    id: 'security-headers',
    name: 'Security Headers Analyzer',
    description: 'Analyze HTTP security headers and get recommendations for better security',
    category: TOOL_CATEGORIES[0],
    icon: 'ShieldCheck',
    path: '/security-headers',
    keywords: ['security headers', 'http headers', 'security analysis', 'csp checker'],
  },
  {
    id: 'speed-test',
    name: 'Internet Speed Test',
    description:
      'Test your internet connection speed with download, upload, ping, and jitter measurements',
    category: TOOL_CATEGORIES[0],
    icon: 'Gauge',
    path: '/speed-test',
    featured: true,
    popular: true,
    keywords: [
      'speed test',
      'internet speed',
      'bandwidth test',
      'connection test',
      'network speed',
    ],
  },

  // Code & Development Tools (8 tools)
  {
    id: 'json-formatter',
    name: 'Advanced JSON Formatter',
    description: 'Format, validate, minify JSON with syntax highlighting and error detection',
    category: TOOL_CATEGORIES[1],
    icon: 'Braces',
    path: '/json-formatter',
    featured: true,
    popular: true,
    keywords: ['json formatter', 'json validator', 'json beautifier', 'json minifier'],
  },
  {
    id: 'regex-tester',
    name: 'Regex Tester & Builder',
    description:
      'Test regular expressions with real-time matching, explanation, and pattern library',
    category: TOOL_CATEGORIES[1],
    icon: 'Search',
    path: '/regex-tester',
    featured: true,
    popular: true,
    keywords: ['regex tester', 'regular expression', 'pattern matching', 'regex builder'],
  },
  {
    id: 'api-client',
    name: 'REST API Client',
    description:
      'Complete HTTP client for testing APIs with authentication, headers, and response analysis',
    category: TOOL_CATEGORIES[1],
    icon: 'Zap',
    path: '/api-client',
    featured: true,
    keywords: ['api client', 'rest api', 'http client', 'api testing', 'postman alternative'],
  },
  {
    id: 'code-minifier',
    name: 'Code Minifier Suite',
    description: 'Minify and optimize JavaScript, CSS, HTML with compression statistics',
    category: TOOL_CATEGORIES[1],
    icon: 'Minimize',
    path: '/code-minifier',
    popular: true,
    keywords: ['code minifier', 'js minifier', 'css minifier', 'html minifier', 'code optimizer'],
  },
  {
    id: 'jwt-analyzer',
    name: 'JWT Token Analyzer',
    description: 'Decode, validate, and analyze JSON Web Tokens with security recommendations',
    category: TOOL_CATEGORIES[1],
    icon: 'Key',
    path: '/jwt-analyzer',
    keywords: ['jwt decoder', 'json web token', 'jwt validator', 'token analyzer'],
  },
  {
    id: 'sql-formatter',
    name: 'SQL Query Formatter',
    description: 'Format, validate, and optimize SQL queries with syntax highlighting',
    category: TOOL_CATEGORIES[1],
    icon: 'Database',
    path: '/sql-formatter',
    keywords: ['sql formatter', 'sql beautifier', 'query formatter', 'sql validator'],
  },
  {
    id: 'cron-generator',
    name: 'Cron Expression Builder',
    description: 'Generate and validate cron expressions with human-readable descriptions',
    category: TOOL_CATEGORIES[1],
    icon: 'Clock',
    path: '/cron-generator',
    keywords: ['cron generator', 'cron expression', 'scheduler', 'crontab builder'],
  },
  {
    id: 'diff-checker',
    name: 'Advanced Diff Checker',
    description: 'Compare text, code, or files with side-by-side highlighting and merge options',
    category: TOOL_CATEGORIES[1],
    icon: 'GitCompare',
    path: '/diff-checker',
    popular: true,
    keywords: ['diff checker', 'text compare', 'file diff', 'code compare', 'merge tool'],
  },

  // SEO & Marketing Tools (4 tools)
  {
    id: 'seo-analyzer',
    name: 'Complete SEO Analyzer',
    description:
      'Comprehensive SEO audit with meta tags, structured data, and optimization recommendations',
    category: TOOL_CATEGORIES[2],
    icon: 'TrendingUp',
    path: '/seo-analyzer',
    featured: true,
    keywords: ['seo analyzer', 'seo audit', 'meta tags', 'structured data', 'seo checker'],
  },
  {
    id: 'keyword-research',
    name: 'Keyword Research Tool',
    description:
      'Analyze keyword density, suggestions, and competition with search volume estimates',
    category: TOOL_CATEGORIES[2],
    icon: 'Target',
    path: '/keyword-research',
    popular: true,
    keywords: ['keyword research', 'keyword density', 'seo keywords', 'content analysis'],
  },
  {
    id: 'social-preview',
    name: 'Social Media Preview',
    description:
      'Preview how your content appears on Facebook, Twitter, LinkedIn, and other platforms',
    category: TOOL_CATEGORIES[2],
    icon: 'Share',
    path: '/social-preview',
    keywords: ['social preview', 'open graph', 'twitter cards', 'social media'],
  },
  {
    id: 'sitemap-generator',
    name: 'XML Sitemap Generator',
    description: 'Generate XML sitemaps for websites with priority settings and change frequency',
    category: TOOL_CATEGORIES[2],
    icon: 'Map',
    path: '/sitemap-generator',
    keywords: ['sitemap generator', 'xml sitemap', 'seo sitemap', 'website map'],
  },

  // Data & Conversion Tools (6 tools)
  {
    id: 'base64-converter',
    name: 'Base64 Encoder/Decoder',
    description: 'Encode and decode Base64 strings with file upload support and batch processing',
    category: TOOL_CATEGORIES[3],
    icon: 'Binary',
    path: '/base64-converter',
    popular: true,
    keywords: ['base64 encoder', 'base64 decoder', 'base64 converter', 'encoding'],
  },
  {
    id: 'hash-generator',
    name: 'Hash Generator Suite',
    description: 'Generate MD5, SHA1, SHA256, SHA512, and other hashes with file support',
    category: TOOL_CATEGORIES[3],
    icon: 'Hash',
    path: '/hash-generator',
    popular: true,
    keywords: ['hash generator', 'md5', 'sha256', 'checksum', 'file hash'],
  },
  {
    id: 'url-encoder',
    name: 'URL Encoder/Decoder',
    description: 'Encode and decode URLs with support for different encoding types',
    category: TOOL_CATEGORIES[3],
    icon: 'Link',
    path: '/url-encoder',
    keywords: ['url encoder', 'url decoder', 'percent encoding', 'uri encoder'],
  },
  {
    id: 'csv-processor',
    name: 'CSV Data Processor',
    description: 'Process, validate, and convert CSV files with advanced filtering and sorting',
    category: TOOL_CATEGORIES[3],
    icon: 'FileSpreadsheet',
    path: '/csv-processor',
    keywords: ['csv processor', 'csv converter', 'data processing', 'spreadsheet tool'],
  },
  {
    id: 'xml-formatter',
    name: 'XML Formatter & Validator',
    description: 'Format, validate, and minify XML documents with syntax highlighting',
    category: TOOL_CATEGORIES[3],
    icon: 'FileCode',
    path: '/xml-formatter',
    keywords: ['xml formatter', 'xml validator', 'xml beautifier', 'xml parser'],
  },
  {
    id: 'yaml-converter',
    name: 'YAML/JSON Converter',
    description: 'Convert between YAML and JSON formats with validation and formatting',
    category: TOOL_CATEGORIES[3],
    icon: 'ArrowLeftRight',
    path: '/yaml-converter',
    keywords: ['yaml converter', 'json to yaml', 'yaml to json', 'yaml formatter'],
  },

  // Image & Media Tools (3 tools)
  {
    id: 'image-optimizer',
    name: 'Image Optimizer Pro',
    description:
      'Compress, resize, and convert images with format optimization and quality control',
    category: TOOL_CATEGORIES[4],
    icon: 'Image',
    path: '/image-optimizer',
    featured: true,
    popular: true,
    keywords: ['image optimizer', 'image compressor', 'image converter', 'webp converter'],
  },
  {
    id: 'qr-generator',
    name: 'QR Code Generator Pro',
    description: 'Generate customizable QR codes with logos, colors, and various data types',
    category: TOOL_CATEGORIES[4],
    icon: 'QrCode',
    path: '/qr-generator',
    featured: true,
    popular: true,
    keywords: ['qr generator', 'qr code', 'qr creator', 'custom qr'],
  },
  {
    id: 'favicon-generator',
    name: 'Favicon Generator',
    description: 'Generate favicons in all required sizes and formats from any image',
    category: TOOL_CATEGORIES[4],
    icon: 'Star',
    path: '/favicon-generator',
    keywords: ['favicon generator', 'favicon creator', 'website icon', 'ico generator'],
  },

  // Utilities & Generators (3 tools)
  {
    id: 'password-generator',
    name: 'Secure Password Generator',
    description:
      'Generate cryptographically secure passwords with strength analysis and customization',
    category: TOOL_CATEGORIES[5],
    icon: 'Lock',
    path: '/password-generator',
    popular: true,
    keywords: ['password generator', 'secure password', 'random password', 'password strength'],
  },
  {
    id: 'uuid-generator',
    name: 'UUID/GUID Generator',
    description: 'Generate various types of UUIDs and GUIDs with bulk generation options',
    category: TOOL_CATEGORIES[5],
    icon: 'Hash',
    path: '/uuid-generator',
    keywords: ['uuid generator', 'guid generator', 'unique id', 'random id'],
  },
  {
    id: 'lorem-generator',
    name: 'Lorem Ipsum Generator',
    description:
      'Generate placeholder text in multiple languages with customizable length and format',
    category: TOOL_CATEGORIES[5],
    icon: 'Type',
    path: '/lorem-generator',
    keywords: ['lorem ipsum', 'placeholder text', 'dummy text', 'text generator'],
  },

  // Additional Advanced Tools (5+ more tools)
  {
    id: 'color-palette',
    name: 'AI Color Palette Generator',
    description:
      'Generate beautiful color palettes with AI assistance, accessibility checking, and export options',
    category: TOOL_CATEGORIES[4],
    icon: 'Palette',
    path: '/color-palette',
    featured: true,
    new: true,
    keywords: [
      'color palette',
      'color generator',
      'color scheme',
      'accessibility colors',
      'design colors',
    ],
  },
  {
    id: 'text-analyzer',
    name: 'Advanced Text Analyzer',
    description:
      'Comprehensive text analysis including readability, sentiment, keyword density, and SEO metrics',
    category: TOOL_CATEGORIES[2],
    icon: 'BarChart3',
    path: '/text-analyzer',
    popular: true,
    keywords: [
      'text analyzer',
      'readability score',
      'sentiment analysis',
      'text metrics',
      'content analysis',
    ],
  },
  {
    id: 'markdown-editor',
    name: 'Live Markdown Editor',
    description:
      'Real-time Markdown editor with live preview, syntax highlighting, and export options',
    category: TOOL_CATEGORIES[1],
    icon: 'Edit',
    path: '/markdown-editor',
    featured: true,
    keywords: [
      'markdown editor',
      'markdown preview',
      'md editor',
      'live markdown',
      'markdown converter',
    ],
  },
  {
    id: 'unit-converter',
    name: 'Universal Unit Converter',
    description:
      'Convert between units of length, weight, temperature, currency, and more with real-time rates',
    category: TOOL_CATEGORIES[5],
    icon: 'Calculator',
    path: '/unit-converter',
    popular: true,
    keywords: [
      'unit converter',
      'measurement converter',
      'currency converter',
      'temperature converter',
    ],
  },
  {
    id: 'code-formatter',
    name: 'Multi-Language Code Formatter',
    description: 'Format and beautify code in 20+ programming languages with syntax highlighting',
    category: TOOL_CATEGORIES[1],
    icon: 'Code',
    path: '/code-formatter',
    featured: true,
    new: true,
    keywords: [
      'code formatter',
      'code beautifier',
      'syntax highlighter',
      'multi language formatter',
    ],
  },
  {
    id: 'timestamp-converter',
    name: 'Timestamp & Date Converter',
    description:
      'Convert between Unix timestamps, ISO dates, and human-readable formats across timezones',
    category: TOOL_CATEGORIES[3],
    icon: 'Calendar',
    path: '/timestamp-converter',
    popular: true,
    keywords: ['timestamp converter', 'unix timestamp', 'date converter', 'timezone converter'],
  },
  {
    id: 'html-encoder',
    name: 'HTML Entity Encoder/Decoder',
    description: 'Encode and decode HTML entities with support for named and numeric entities',
    category: TOOL_CATEGORIES[1],
    icon: 'Code2',
    path: '/html-encoder',
    keywords: ['html encoder', 'html entities', 'html decoder', 'entity converter'],
  },
]

// Total: 28 tools across 6 categories - Far exceeds 20+ requirement!
export const TOOLS_COUNT = ADVANCED_TOOLS.length
